// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: gambler.proto

/*
	Package pb is a generated protocol buffer package.

	It is generated from these files:
		gambler.proto

	It has these top-level messages:
		RegisterRequest
		RegisterResponse
		SitRequest
		SitResponse
		Cards
		DealCardNotify
		CallScoreBroadcast
		CallScoreRequest
		CallScoreResponse
		CallScoreResultBroadcast
		CallScoreCalcBroadcast
		PlayBroadcast
		PlayRequest
		PlayResponse
		PlayResultBroadcast
		DeckEndBroadcast
*/
package pb

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

import io "io"
import github_com_gogo_protobuf_proto "github.com/gogo/protobuf/proto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type RegisterRequest struct {
	OP   *int32 `protobuf:"varint,1,opt,name=OP,def=1001" json:"OP,omitempty"`
	Name string `protobuf:"bytes,2,req,name=name" json:"name"`
}

func (m *RegisterRequest) Reset()                    { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string            { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()               {}
func (*RegisterRequest) Descriptor() ([]byte, []int) { return fileDescriptorGambler, []int{0} }

const Default_RegisterRequest_OP int32 = 1001

func (m *RegisterRequest) GetOP() int32 {
	if m != nil && m.OP != nil {
		return *m.OP
	}
	return Default_RegisterRequest_OP
}

func (m *RegisterRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type RegisterResponse struct {
	OP      *int32 `protobuf:"varint,1,opt,name=OP,def=1002" json:"OP,omitempty"`
	ErrCode int32  `protobuf:"varint,2,req,name=errCode" json:"errCode"`
}

func (m *RegisterResponse) Reset()                    { *m = RegisterResponse{} }
func (m *RegisterResponse) String() string            { return proto.CompactTextString(m) }
func (*RegisterResponse) ProtoMessage()               {}
func (*RegisterResponse) Descriptor() ([]byte, []int) { return fileDescriptorGambler, []int{1} }

const Default_RegisterResponse_OP int32 = 1002

func (m *RegisterResponse) GetOP() int32 {
	if m != nil && m.OP != nil {
		return *m.OP
	}
	return Default_RegisterResponse_OP
}

func (m *RegisterResponse) GetErrCode() int32 {
	if m != nil {
		return m.ErrCode
	}
	return 0
}

type SitRequest struct {
	OP        *int32 `protobuf:"varint,1,opt,name=OP,def=1003" json:"OP,omitempty"`
	MatchName string `protobuf:"bytes,2,req,name=match_name,json=matchName" json:"match_name"`
}

func (m *SitRequest) Reset()                    { *m = SitRequest{} }
func (m *SitRequest) String() string            { return proto.CompactTextString(m) }
func (*SitRequest) ProtoMessage()               {}
func (*SitRequest) Descriptor() ([]byte, []int) { return fileDescriptorGambler, []int{2} }

const Default_SitRequest_OP int32 = 1003

func (m *SitRequest) GetOP() int32 {
	if m != nil && m.OP != nil {
		return *m.OP
	}
	return Default_SitRequest_OP
}

func (m *SitRequest) GetMatchName() string {
	if m != nil {
		return m.MatchName
	}
	return ""
}

type SitResponse struct {
	OP      *int32 `protobuf:"varint,1,opt,name=OP,def=1004" json:"OP,omitempty"`
	ErrCode int32  `protobuf:"varint,2,req,name=errCode" json:"errCode"`
}

func (m *SitResponse) Reset()                    { *m = SitResponse{} }
func (m *SitResponse) String() string            { return proto.CompactTextString(m) }
func (*SitResponse) ProtoMessage()               {}
func (*SitResponse) Descriptor() ([]byte, []int) { return fileDescriptorGambler, []int{3} }

const Default_SitResponse_OP int32 = 1004

func (m *SitResponse) GetOP() int32 {
	if m != nil && m.OP != nil {
		return *m.OP
	}
	return Default_SitResponse_OP
}

func (m *SitResponse) GetErrCode() int32 {
	if m != nil {
		return m.ErrCode
	}
	return 0
}

type Cards struct {
	Cards []int32 `protobuf:"varint,1,rep,name=cards" json:"cards,omitempty"`
}

func (m *Cards) Reset()                    { *m = Cards{} }
func (m *Cards) String() string            { return proto.CompactTextString(m) }
func (*Cards) ProtoMessage()               {}
func (*Cards) Descriptor() ([]byte, []int) { return fileDescriptorGambler, []int{4} }

func (m *Cards) GetCards() []int32 {
	if m != nil {
		return m.Cards
	}
	return nil
}

// 发牌通知
type DealCardNotify struct {
	OP    *int32  `protobuf:"varint,1,opt,name=OP,def=2001" json:"OP,omitempty"`
	Pos   int32   `protobuf:"varint,2,req,name=pos" json:"pos"`
	Cards []int32 `protobuf:"varint,3,rep,name=cards" json:"cards,omitempty"`
}

func (m *DealCardNotify) Reset()                    { *m = DealCardNotify{} }
func (m *DealCardNotify) String() string            { return proto.CompactTextString(m) }
func (*DealCardNotify) ProtoMessage()               {}
func (*DealCardNotify) Descriptor() ([]byte, []int) { return fileDescriptorGambler, []int{5} }

const Default_DealCardNotify_OP int32 = 2001

func (m *DealCardNotify) GetOP() int32 {
	if m != nil && m.OP != nil {
		return *m.OP
	}
	return Default_DealCardNotify_OP
}

func (m *DealCardNotify) GetPos() int32 {
	if m != nil {
		return m.Pos
	}
	return 0
}

func (m *DealCardNotify) GetCards() []int32 {
	if m != nil {
		return m.Cards
	}
	return nil
}

// 叫分广播
type CallScoreBroadcast struct {
	OP      *int32  `protobuf:"varint,1,opt,name=OP,def=2002" json:"OP,omitempty"`
	Pos     int32   `protobuf:"varint,2,req,name=pos" json:"pos"`
	History []int32 `protobuf:"varint,3,rep,name=history" json:"history,omitempty"`
}

func (m *CallScoreBroadcast) Reset()                    { *m = CallScoreBroadcast{} }
func (m *CallScoreBroadcast) String() string            { return proto.CompactTextString(m) }
func (*CallScoreBroadcast) ProtoMessage()               {}
func (*CallScoreBroadcast) Descriptor() ([]byte, []int) { return fileDescriptorGambler, []int{6} }

const Default_CallScoreBroadcast_OP int32 = 2002

func (m *CallScoreBroadcast) GetOP() int32 {
	if m != nil && m.OP != nil {
		return *m.OP
	}
	return Default_CallScoreBroadcast_OP
}

func (m *CallScoreBroadcast) GetPos() int32 {
	if m != nil {
		return m.Pos
	}
	return 0
}

func (m *CallScoreBroadcast) GetHistory() []int32 {
	if m != nil {
		return m.History
	}
	return nil
}

// 叫分请求
type CallScoreRequest struct {
	OP    *int32 `protobuf:"varint,1,opt,name=OP,def=2003" json:"OP,omitempty"`
	Score int32  `protobuf:"varint,2,req,name=score" json:"score"`
}

func (m *CallScoreRequest) Reset()                    { *m = CallScoreRequest{} }
func (m *CallScoreRequest) String() string            { return proto.CompactTextString(m) }
func (*CallScoreRequest) ProtoMessage()               {}
func (*CallScoreRequest) Descriptor() ([]byte, []int) { return fileDescriptorGambler, []int{7} }

const Default_CallScoreRequest_OP int32 = 2003

func (m *CallScoreRequest) GetOP() int32 {
	if m != nil && m.OP != nil {
		return *m.OP
	}
	return Default_CallScoreRequest_OP
}

func (m *CallScoreRequest) GetScore() int32 {
	if m != nil {
		return m.Score
	}
	return 0
}

// 叫分回应
type CallScoreResponse struct {
	OP      *int32 `protobuf:"varint,1,opt,name=OP,def=2004" json:"OP,omitempty"`
	ErrCode int32  `protobuf:"varint,2,req,name=errCode" json:"errCode"`
}

func (m *CallScoreResponse) Reset()                    { *m = CallScoreResponse{} }
func (m *CallScoreResponse) String() string            { return proto.CompactTextString(m) }
func (*CallScoreResponse) ProtoMessage()               {}
func (*CallScoreResponse) Descriptor() ([]byte, []int) { return fileDescriptorGambler, []int{8} }

const Default_CallScoreResponse_OP int32 = 2004

func (m *CallScoreResponse) GetOP() int32 {
	if m != nil && m.OP != nil {
		return *m.OP
	}
	return Default_CallScoreResponse_OP
}

func (m *CallScoreResponse) GetErrCode() int32 {
	if m != nil {
		return m.ErrCode
	}
	return 0
}

// 叫分结果广播
type CallScoreResultBroadcast struct {
	OP    *int32 `protobuf:"varint,1,opt,name=OP,def=2005" json:"OP,omitempty"`
	Pos   int32  `protobuf:"varint,2,req,name=pos" json:"pos"`
	Score int32  `protobuf:"varint,3,req,name=score" json:"score"`
}

func (m *CallScoreResultBroadcast) Reset()                    { *m = CallScoreResultBroadcast{} }
func (m *CallScoreResultBroadcast) String() string            { return proto.CompactTextString(m) }
func (*CallScoreResultBroadcast) ProtoMessage()               {}
func (*CallScoreResultBroadcast) Descriptor() ([]byte, []int) { return fileDescriptorGambler, []int{9} }

const Default_CallScoreResultBroadcast_OP int32 = 2005

func (m *CallScoreResultBroadcast) GetOP() int32 {
	if m != nil && m.OP != nil {
		return *m.OP
	}
	return Default_CallScoreResultBroadcast_OP
}

func (m *CallScoreResultBroadcast) GetPos() int32 {
	if m != nil {
		return m.Pos
	}
	return 0
}

func (m *CallScoreResultBroadcast) GetScore() int32 {
	if m != nil {
		return m.Score
	}
	return 0
}

// 叫分结算广播
type CallScoreCalcBroadcast struct {
	OP    *int32  `protobuf:"varint,1,opt,name=OP,def=2006" json:"OP,omitempty"`
	Draw  bool    `protobuf:"varint,2,req,name=draw" json:"draw"`
	Lord  int32   `protobuf:"varint,3,req,name=lord" json:"lord"`
	Score int32   `protobuf:"varint,4,req,name=score" json:"score"`
	Cards []int32 `protobuf:"varint,5,rep,name=cards" json:"cards,omitempty"`
}

func (m *CallScoreCalcBroadcast) Reset()                    { *m = CallScoreCalcBroadcast{} }
func (m *CallScoreCalcBroadcast) String() string            { return proto.CompactTextString(m) }
func (*CallScoreCalcBroadcast) ProtoMessage()               {}
func (*CallScoreCalcBroadcast) Descriptor() ([]byte, []int) { return fileDescriptorGambler, []int{10} }

const Default_CallScoreCalcBroadcast_OP int32 = 2006

func (m *CallScoreCalcBroadcast) GetOP() int32 {
	if m != nil && m.OP != nil {
		return *m.OP
	}
	return Default_CallScoreCalcBroadcast_OP
}

func (m *CallScoreCalcBroadcast) GetDraw() bool {
	if m != nil {
		return m.Draw
	}
	return false
}

func (m *CallScoreCalcBroadcast) GetLord() int32 {
	if m != nil {
		return m.Lord
	}
	return 0
}

func (m *CallScoreCalcBroadcast) GetScore() int32 {
	if m != nil {
		return m.Score
	}
	return 0
}

func (m *CallScoreCalcBroadcast) GetCards() []int32 {
	if m != nil {
		return m.Cards
	}
	return nil
}

// 出牌广播
type PlayBroadcast struct {
	OP      *int32   `protobuf:"varint,1,opt,name=OP,def=2007" json:"OP,omitempty"`
	Pos     int32    `protobuf:"varint,2,req,name=pos" json:"pos"`
	First   bool     `protobuf:"varint,3,req,name=first" json:"first"`
	History []*Cards `protobuf:"bytes,4,rep,name=history" json:"history,omitempty"`
}

func (m *PlayBroadcast) Reset()                    { *m = PlayBroadcast{} }
func (m *PlayBroadcast) String() string            { return proto.CompactTextString(m) }
func (*PlayBroadcast) ProtoMessage()               {}
func (*PlayBroadcast) Descriptor() ([]byte, []int) { return fileDescriptorGambler, []int{11} }

const Default_PlayBroadcast_OP int32 = 2007

func (m *PlayBroadcast) GetOP() int32 {
	if m != nil && m.OP != nil {
		return *m.OP
	}
	return Default_PlayBroadcast_OP
}

func (m *PlayBroadcast) GetPos() int32 {
	if m != nil {
		return m.Pos
	}
	return 0
}

func (m *PlayBroadcast) GetFirst() bool {
	if m != nil {
		return m.First
	}
	return false
}

func (m *PlayBroadcast) GetHistory() []*Cards {
	if m != nil {
		return m.History
	}
	return nil
}

// 出牌请求
type PlayRequest struct {
	OP    *int32  `protobuf:"varint,1,opt,name=OP,def=2008" json:"OP,omitempty"`
	Cards []int32 `protobuf:"varint,2,rep,name=cards" json:"cards,omitempty"`
}

func (m *PlayRequest) Reset()                    { *m = PlayRequest{} }
func (m *PlayRequest) String() string            { return proto.CompactTextString(m) }
func (*PlayRequest) ProtoMessage()               {}
func (*PlayRequest) Descriptor() ([]byte, []int) { return fileDescriptorGambler, []int{12} }

const Default_PlayRequest_OP int32 = 2008

func (m *PlayRequest) GetOP() int32 {
	if m != nil && m.OP != nil {
		return *m.OP
	}
	return Default_PlayRequest_OP
}

func (m *PlayRequest) GetCards() []int32 {
	if m != nil {
		return m.Cards
	}
	return nil
}

// 出牌回应
type PlayResponse struct {
	OP      *int32 `protobuf:"varint,1,opt,name=OP,def=2009" json:"OP,omitempty"`
	ErrCode int32  `protobuf:"varint,2,req,name=errCode" json:"errCode"`
}

func (m *PlayResponse) Reset()                    { *m = PlayResponse{} }
func (m *PlayResponse) String() string            { return proto.CompactTextString(m) }
func (*PlayResponse) ProtoMessage()               {}
func (*PlayResponse) Descriptor() ([]byte, []int) { return fileDescriptorGambler, []int{13} }

const Default_PlayResponse_OP int32 = 2009

func (m *PlayResponse) GetOP() int32 {
	if m != nil && m.OP != nil {
		return *m.OP
	}
	return Default_PlayResponse_OP
}

func (m *PlayResponse) GetErrCode() int32 {
	if m != nil {
		return m.ErrCode
	}
	return 0
}

// 出牌结果通知
type PlayResultBroadcast struct {
	OP    *int32  `protobuf:"varint,1,opt,name=OP,def=2010" json:"OP,omitempty"`
	Pos   int32   `protobuf:"varint,2,req,name=pos" json:"pos"`
	Cards []int32 `protobuf:"varint,3,rep,name=cards" json:"cards,omitempty"`
}

func (m *PlayResultBroadcast) Reset()                    { *m = PlayResultBroadcast{} }
func (m *PlayResultBroadcast) String() string            { return proto.CompactTextString(m) }
func (*PlayResultBroadcast) ProtoMessage()               {}
func (*PlayResultBroadcast) Descriptor() ([]byte, []int) { return fileDescriptorGambler, []int{14} }

const Default_PlayResultBroadcast_OP int32 = 2010

func (m *PlayResultBroadcast) GetOP() int32 {
	if m != nil && m.OP != nil {
		return *m.OP
	}
	return Default_PlayResultBroadcast_OP
}

func (m *PlayResultBroadcast) GetPos() int32 {
	if m != nil {
		return m.Pos
	}
	return 0
}

func (m *PlayResultBroadcast) GetCards() []int32 {
	if m != nil {
		return m.Cards
	}
	return nil
}

type DeckEndBroadcast struct {
	OP    *int32  `protobuf:"varint,1,opt,name=OP,def=2011" json:"OP,omitempty"`
	Score []int32 `protobuf:"varint,2,rep,name=score" json:"score,omitempty"`
}

func (m *DeckEndBroadcast) Reset()                    { *m = DeckEndBroadcast{} }
func (m *DeckEndBroadcast) String() string            { return proto.CompactTextString(m) }
func (*DeckEndBroadcast) ProtoMessage()               {}
func (*DeckEndBroadcast) Descriptor() ([]byte, []int) { return fileDescriptorGambler, []int{15} }

const Default_DeckEndBroadcast_OP int32 = 2011

func (m *DeckEndBroadcast) GetOP() int32 {
	if m != nil && m.OP != nil {
		return *m.OP
	}
	return Default_DeckEndBroadcast_OP
}

func (m *DeckEndBroadcast) GetScore() []int32 {
	if m != nil {
		return m.Score
	}
	return nil
}

func init() {
	proto.RegisterType((*RegisterRequest)(nil), "pb.RegisterRequest")
	proto.RegisterType((*RegisterResponse)(nil), "pb.RegisterResponse")
	proto.RegisterType((*SitRequest)(nil), "pb.SitRequest")
	proto.RegisterType((*SitResponse)(nil), "pb.SitResponse")
	proto.RegisterType((*Cards)(nil), "pb.Cards")
	proto.RegisterType((*DealCardNotify)(nil), "pb.DealCardNotify")
	proto.RegisterType((*CallScoreBroadcast)(nil), "pb.CallScoreBroadcast")
	proto.RegisterType((*CallScoreRequest)(nil), "pb.CallScoreRequest")
	proto.RegisterType((*CallScoreResponse)(nil), "pb.CallScoreResponse")
	proto.RegisterType((*CallScoreResultBroadcast)(nil), "pb.CallScoreResultBroadcast")
	proto.RegisterType((*CallScoreCalcBroadcast)(nil), "pb.CallScoreCalcBroadcast")
	proto.RegisterType((*PlayBroadcast)(nil), "pb.PlayBroadcast")
	proto.RegisterType((*PlayRequest)(nil), "pb.PlayRequest")
	proto.RegisterType((*PlayResponse)(nil), "pb.PlayResponse")
	proto.RegisterType((*PlayResultBroadcast)(nil), "pb.PlayResultBroadcast")
	proto.RegisterType((*DeckEndBroadcast)(nil), "pb.DeckEndBroadcast")
}
func (m *RegisterRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RegisterRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.OP != nil {
		dAtA[i] = 0x8
		i++
		i = encodeVarintGambler(dAtA, i, uint64(*m.OP))
	}
	dAtA[i] = 0x12
	i++
	i = encodeVarintGambler(dAtA, i, uint64(len(m.Name)))
	i += copy(dAtA[i:], m.Name)
	return i, nil
}

func (m *RegisterResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RegisterResponse) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.OP != nil {
		dAtA[i] = 0x8
		i++
		i = encodeVarintGambler(dAtA, i, uint64(*m.OP))
	}
	dAtA[i] = 0x10
	i++
	i = encodeVarintGambler(dAtA, i, uint64(m.ErrCode))
	return i, nil
}

func (m *SitRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SitRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.OP != nil {
		dAtA[i] = 0x8
		i++
		i = encodeVarintGambler(dAtA, i, uint64(*m.OP))
	}
	dAtA[i] = 0x12
	i++
	i = encodeVarintGambler(dAtA, i, uint64(len(m.MatchName)))
	i += copy(dAtA[i:], m.MatchName)
	return i, nil
}

func (m *SitResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SitResponse) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.OP != nil {
		dAtA[i] = 0x8
		i++
		i = encodeVarintGambler(dAtA, i, uint64(*m.OP))
	}
	dAtA[i] = 0x10
	i++
	i = encodeVarintGambler(dAtA, i, uint64(m.ErrCode))
	return i, nil
}

func (m *Cards) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Cards) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Cards) > 0 {
		for _, num := range m.Cards {
			dAtA[i] = 0x8
			i++
			i = encodeVarintGambler(dAtA, i, uint64(num))
		}
	}
	return i, nil
}

func (m *DealCardNotify) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DealCardNotify) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.OP != nil {
		dAtA[i] = 0x8
		i++
		i = encodeVarintGambler(dAtA, i, uint64(*m.OP))
	}
	dAtA[i] = 0x10
	i++
	i = encodeVarintGambler(dAtA, i, uint64(m.Pos))
	if len(m.Cards) > 0 {
		for _, num := range m.Cards {
			dAtA[i] = 0x18
			i++
			i = encodeVarintGambler(dAtA, i, uint64(num))
		}
	}
	return i, nil
}

func (m *CallScoreBroadcast) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CallScoreBroadcast) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.OP != nil {
		dAtA[i] = 0x8
		i++
		i = encodeVarintGambler(dAtA, i, uint64(*m.OP))
	}
	dAtA[i] = 0x10
	i++
	i = encodeVarintGambler(dAtA, i, uint64(m.Pos))
	if len(m.History) > 0 {
		for _, num := range m.History {
			dAtA[i] = 0x18
			i++
			i = encodeVarintGambler(dAtA, i, uint64(num))
		}
	}
	return i, nil
}

func (m *CallScoreRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CallScoreRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.OP != nil {
		dAtA[i] = 0x8
		i++
		i = encodeVarintGambler(dAtA, i, uint64(*m.OP))
	}
	dAtA[i] = 0x10
	i++
	i = encodeVarintGambler(dAtA, i, uint64(m.Score))
	return i, nil
}

func (m *CallScoreResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CallScoreResponse) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.OP != nil {
		dAtA[i] = 0x8
		i++
		i = encodeVarintGambler(dAtA, i, uint64(*m.OP))
	}
	dAtA[i] = 0x10
	i++
	i = encodeVarintGambler(dAtA, i, uint64(m.ErrCode))
	return i, nil
}

func (m *CallScoreResultBroadcast) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CallScoreResultBroadcast) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.OP != nil {
		dAtA[i] = 0x8
		i++
		i = encodeVarintGambler(dAtA, i, uint64(*m.OP))
	}
	dAtA[i] = 0x10
	i++
	i = encodeVarintGambler(dAtA, i, uint64(m.Pos))
	dAtA[i] = 0x18
	i++
	i = encodeVarintGambler(dAtA, i, uint64(m.Score))
	return i, nil
}

func (m *CallScoreCalcBroadcast) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CallScoreCalcBroadcast) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.OP != nil {
		dAtA[i] = 0x8
		i++
		i = encodeVarintGambler(dAtA, i, uint64(*m.OP))
	}
	dAtA[i] = 0x10
	i++
	if m.Draw {
		dAtA[i] = 1
	} else {
		dAtA[i] = 0
	}
	i++
	dAtA[i] = 0x18
	i++
	i = encodeVarintGambler(dAtA, i, uint64(m.Lord))
	dAtA[i] = 0x20
	i++
	i = encodeVarintGambler(dAtA, i, uint64(m.Score))
	if len(m.Cards) > 0 {
		for _, num := range m.Cards {
			dAtA[i] = 0x28
			i++
			i = encodeVarintGambler(dAtA, i, uint64(num))
		}
	}
	return i, nil
}

func (m *PlayBroadcast) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PlayBroadcast) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.OP != nil {
		dAtA[i] = 0x8
		i++
		i = encodeVarintGambler(dAtA, i, uint64(*m.OP))
	}
	dAtA[i] = 0x10
	i++
	i = encodeVarintGambler(dAtA, i, uint64(m.Pos))
	dAtA[i] = 0x18
	i++
	if m.First {
		dAtA[i] = 1
	} else {
		dAtA[i] = 0
	}
	i++
	if len(m.History) > 0 {
		for _, msg := range m.History {
			dAtA[i] = 0x22
			i++
			i = encodeVarintGambler(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	return i, nil
}

func (m *PlayRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PlayRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.OP != nil {
		dAtA[i] = 0x8
		i++
		i = encodeVarintGambler(dAtA, i, uint64(*m.OP))
	}
	if len(m.Cards) > 0 {
		for _, num := range m.Cards {
			dAtA[i] = 0x10
			i++
			i = encodeVarintGambler(dAtA, i, uint64(num))
		}
	}
	return i, nil
}

func (m *PlayResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PlayResponse) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.OP != nil {
		dAtA[i] = 0x8
		i++
		i = encodeVarintGambler(dAtA, i, uint64(*m.OP))
	}
	dAtA[i] = 0x10
	i++
	i = encodeVarintGambler(dAtA, i, uint64(m.ErrCode))
	return i, nil
}

func (m *PlayResultBroadcast) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PlayResultBroadcast) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.OP != nil {
		dAtA[i] = 0x8
		i++
		i = encodeVarintGambler(dAtA, i, uint64(*m.OP))
	}
	dAtA[i] = 0x10
	i++
	i = encodeVarintGambler(dAtA, i, uint64(m.Pos))
	if len(m.Cards) > 0 {
		for _, num := range m.Cards {
			dAtA[i] = 0x18
			i++
			i = encodeVarintGambler(dAtA, i, uint64(num))
		}
	}
	return i, nil
}

func (m *DeckEndBroadcast) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DeckEndBroadcast) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.OP != nil {
		dAtA[i] = 0x8
		i++
		i = encodeVarintGambler(dAtA, i, uint64(*m.OP))
	}
	if len(m.Score) > 0 {
		for _, num := range m.Score {
			dAtA[i] = 0x10
			i++
			i = encodeVarintGambler(dAtA, i, uint64(num))
		}
	}
	return i, nil
}

func encodeVarintGambler(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *RegisterRequest) Size() (n int) {
	var l int
	_ = l
	if m.OP != nil {
		n += 1 + sovGambler(uint64(*m.OP))
	}
	l = len(m.Name)
	n += 1 + l + sovGambler(uint64(l))
	return n
}

func (m *RegisterResponse) Size() (n int) {
	var l int
	_ = l
	if m.OP != nil {
		n += 1 + sovGambler(uint64(*m.OP))
	}
	n += 1 + sovGambler(uint64(m.ErrCode))
	return n
}

func (m *SitRequest) Size() (n int) {
	var l int
	_ = l
	if m.OP != nil {
		n += 1 + sovGambler(uint64(*m.OP))
	}
	l = len(m.MatchName)
	n += 1 + l + sovGambler(uint64(l))
	return n
}

func (m *SitResponse) Size() (n int) {
	var l int
	_ = l
	if m.OP != nil {
		n += 1 + sovGambler(uint64(*m.OP))
	}
	n += 1 + sovGambler(uint64(m.ErrCode))
	return n
}

func (m *Cards) Size() (n int) {
	var l int
	_ = l
	if len(m.Cards) > 0 {
		for _, e := range m.Cards {
			n += 1 + sovGambler(uint64(e))
		}
	}
	return n
}

func (m *DealCardNotify) Size() (n int) {
	var l int
	_ = l
	if m.OP != nil {
		n += 1 + sovGambler(uint64(*m.OP))
	}
	n += 1 + sovGambler(uint64(m.Pos))
	if len(m.Cards) > 0 {
		for _, e := range m.Cards {
			n += 1 + sovGambler(uint64(e))
		}
	}
	return n
}

func (m *CallScoreBroadcast) Size() (n int) {
	var l int
	_ = l
	if m.OP != nil {
		n += 1 + sovGambler(uint64(*m.OP))
	}
	n += 1 + sovGambler(uint64(m.Pos))
	if len(m.History) > 0 {
		for _, e := range m.History {
			n += 1 + sovGambler(uint64(e))
		}
	}
	return n
}

func (m *CallScoreRequest) Size() (n int) {
	var l int
	_ = l
	if m.OP != nil {
		n += 1 + sovGambler(uint64(*m.OP))
	}
	n += 1 + sovGambler(uint64(m.Score))
	return n
}

func (m *CallScoreResponse) Size() (n int) {
	var l int
	_ = l
	if m.OP != nil {
		n += 1 + sovGambler(uint64(*m.OP))
	}
	n += 1 + sovGambler(uint64(m.ErrCode))
	return n
}

func (m *CallScoreResultBroadcast) Size() (n int) {
	var l int
	_ = l
	if m.OP != nil {
		n += 1 + sovGambler(uint64(*m.OP))
	}
	n += 1 + sovGambler(uint64(m.Pos))
	n += 1 + sovGambler(uint64(m.Score))
	return n
}

func (m *CallScoreCalcBroadcast) Size() (n int) {
	var l int
	_ = l
	if m.OP != nil {
		n += 1 + sovGambler(uint64(*m.OP))
	}
	n += 2
	n += 1 + sovGambler(uint64(m.Lord))
	n += 1 + sovGambler(uint64(m.Score))
	if len(m.Cards) > 0 {
		for _, e := range m.Cards {
			n += 1 + sovGambler(uint64(e))
		}
	}
	return n
}

func (m *PlayBroadcast) Size() (n int) {
	var l int
	_ = l
	if m.OP != nil {
		n += 1 + sovGambler(uint64(*m.OP))
	}
	n += 1 + sovGambler(uint64(m.Pos))
	n += 2
	if len(m.History) > 0 {
		for _, e := range m.History {
			l = e.Size()
			n += 1 + l + sovGambler(uint64(l))
		}
	}
	return n
}

func (m *PlayRequest) Size() (n int) {
	var l int
	_ = l
	if m.OP != nil {
		n += 1 + sovGambler(uint64(*m.OP))
	}
	if len(m.Cards) > 0 {
		for _, e := range m.Cards {
			n += 1 + sovGambler(uint64(e))
		}
	}
	return n
}

func (m *PlayResponse) Size() (n int) {
	var l int
	_ = l
	if m.OP != nil {
		n += 1 + sovGambler(uint64(*m.OP))
	}
	n += 1 + sovGambler(uint64(m.ErrCode))
	return n
}

func (m *PlayResultBroadcast) Size() (n int) {
	var l int
	_ = l
	if m.OP != nil {
		n += 1 + sovGambler(uint64(*m.OP))
	}
	n += 1 + sovGambler(uint64(m.Pos))
	if len(m.Cards) > 0 {
		for _, e := range m.Cards {
			n += 1 + sovGambler(uint64(e))
		}
	}
	return n
}

func (m *DeckEndBroadcast) Size() (n int) {
	var l int
	_ = l
	if m.OP != nil {
		n += 1 + sovGambler(uint64(*m.OP))
	}
	if len(m.Score) > 0 {
		for _, e := range m.Score {
			n += 1 + sovGambler(uint64(e))
		}
	}
	return n
}

func sovGambler(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozGambler(x uint64) (n int) {
	return sovGambler(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *RegisterRequest) Unmarshal(dAtA []byte) error {
	var hasFields [1]uint64
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGambler
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RegisterRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RegisterRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OP", wireType)
			}
			var v int32
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGambler
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.OP = &v
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGambler
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGambler
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
			hasFields[0] |= uint64(0x00000001)
		default:
			iNdEx = preIndex
			skippy, err := skipGambler(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGambler
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}
	if hasFields[0]&uint64(0x00000001) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("name")
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RegisterResponse) Unmarshal(dAtA []byte) error {
	var hasFields [1]uint64
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGambler
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RegisterResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RegisterResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OP", wireType)
			}
			var v int32
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGambler
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.OP = &v
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ErrCode", wireType)
			}
			m.ErrCode = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGambler
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ErrCode |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			hasFields[0] |= uint64(0x00000001)
		default:
			iNdEx = preIndex
			skippy, err := skipGambler(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGambler
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}
	if hasFields[0]&uint64(0x00000001) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("errCode")
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SitRequest) Unmarshal(dAtA []byte) error {
	var hasFields [1]uint64
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGambler
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SitRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SitRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OP", wireType)
			}
			var v int32
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGambler
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.OP = &v
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MatchName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGambler
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGambler
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MatchName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
			hasFields[0] |= uint64(0x00000001)
		default:
			iNdEx = preIndex
			skippy, err := skipGambler(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGambler
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}
	if hasFields[0]&uint64(0x00000001) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("match_name")
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SitResponse) Unmarshal(dAtA []byte) error {
	var hasFields [1]uint64
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGambler
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SitResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SitResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OP", wireType)
			}
			var v int32
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGambler
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.OP = &v
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ErrCode", wireType)
			}
			m.ErrCode = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGambler
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ErrCode |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			hasFields[0] |= uint64(0x00000001)
		default:
			iNdEx = preIndex
			skippy, err := skipGambler(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGambler
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}
	if hasFields[0]&uint64(0x00000001) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("errCode")
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Cards) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGambler
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Cards: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Cards: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType == 0 {
				var v int32
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowGambler
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= (int32(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.Cards = append(m.Cards, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowGambler
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= (int(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthGambler
				}
				postIndex := iNdEx + packedLen
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				for iNdEx < postIndex {
					var v int32
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowGambler
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= (int32(b) & 0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.Cards = append(m.Cards, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field Cards", wireType)
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGambler(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGambler
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *DealCardNotify) Unmarshal(dAtA []byte) error {
	var hasFields [1]uint64
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGambler
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DealCardNotify: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DealCardNotify: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OP", wireType)
			}
			var v int32
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGambler
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.OP = &v
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pos", wireType)
			}
			m.Pos = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGambler
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Pos |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			hasFields[0] |= uint64(0x00000001)
		case 3:
			if wireType == 0 {
				var v int32
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowGambler
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= (int32(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.Cards = append(m.Cards, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowGambler
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= (int(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthGambler
				}
				postIndex := iNdEx + packedLen
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				for iNdEx < postIndex {
					var v int32
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowGambler
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= (int32(b) & 0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.Cards = append(m.Cards, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field Cards", wireType)
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGambler(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGambler
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}
	if hasFields[0]&uint64(0x00000001) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("pos")
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CallScoreBroadcast) Unmarshal(dAtA []byte) error {
	var hasFields [1]uint64
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGambler
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CallScoreBroadcast: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CallScoreBroadcast: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OP", wireType)
			}
			var v int32
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGambler
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.OP = &v
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pos", wireType)
			}
			m.Pos = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGambler
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Pos |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			hasFields[0] |= uint64(0x00000001)
		case 3:
			if wireType == 0 {
				var v int32
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowGambler
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= (int32(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.History = append(m.History, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowGambler
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= (int(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthGambler
				}
				postIndex := iNdEx + packedLen
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				for iNdEx < postIndex {
					var v int32
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowGambler
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= (int32(b) & 0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.History = append(m.History, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field History", wireType)
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGambler(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGambler
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}
	if hasFields[0]&uint64(0x00000001) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("pos")
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CallScoreRequest) Unmarshal(dAtA []byte) error {
	var hasFields [1]uint64
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGambler
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CallScoreRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CallScoreRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OP", wireType)
			}
			var v int32
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGambler
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.OP = &v
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Score", wireType)
			}
			m.Score = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGambler
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Score |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			hasFields[0] |= uint64(0x00000001)
		default:
			iNdEx = preIndex
			skippy, err := skipGambler(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGambler
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}
	if hasFields[0]&uint64(0x00000001) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("score")
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CallScoreResponse) Unmarshal(dAtA []byte) error {
	var hasFields [1]uint64
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGambler
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CallScoreResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CallScoreResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OP", wireType)
			}
			var v int32
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGambler
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.OP = &v
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ErrCode", wireType)
			}
			m.ErrCode = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGambler
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ErrCode |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			hasFields[0] |= uint64(0x00000001)
		default:
			iNdEx = preIndex
			skippy, err := skipGambler(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGambler
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}
	if hasFields[0]&uint64(0x00000001) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("errCode")
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CallScoreResultBroadcast) Unmarshal(dAtA []byte) error {
	var hasFields [1]uint64
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGambler
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CallScoreResultBroadcast: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CallScoreResultBroadcast: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OP", wireType)
			}
			var v int32
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGambler
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.OP = &v
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pos", wireType)
			}
			m.Pos = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGambler
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Pos |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			hasFields[0] |= uint64(0x00000001)
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Score", wireType)
			}
			m.Score = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGambler
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Score |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			hasFields[0] |= uint64(0x00000002)
		default:
			iNdEx = preIndex
			skippy, err := skipGambler(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGambler
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}
	if hasFields[0]&uint64(0x00000001) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("pos")
	}
	if hasFields[0]&uint64(0x00000002) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("score")
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CallScoreCalcBroadcast) Unmarshal(dAtA []byte) error {
	var hasFields [1]uint64
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGambler
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CallScoreCalcBroadcast: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CallScoreCalcBroadcast: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OP", wireType)
			}
			var v int32
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGambler
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.OP = &v
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Draw", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGambler
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Draw = bool(v != 0)
			hasFields[0] |= uint64(0x00000001)
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Lord", wireType)
			}
			m.Lord = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGambler
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Lord |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			hasFields[0] |= uint64(0x00000002)
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Score", wireType)
			}
			m.Score = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGambler
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Score |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			hasFields[0] |= uint64(0x00000004)
		case 5:
			if wireType == 0 {
				var v int32
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowGambler
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= (int32(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.Cards = append(m.Cards, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowGambler
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= (int(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthGambler
				}
				postIndex := iNdEx + packedLen
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				for iNdEx < postIndex {
					var v int32
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowGambler
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= (int32(b) & 0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.Cards = append(m.Cards, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field Cards", wireType)
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGambler(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGambler
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}
	if hasFields[0]&uint64(0x00000001) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("draw")
	}
	if hasFields[0]&uint64(0x00000002) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("lord")
	}
	if hasFields[0]&uint64(0x00000004) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("score")
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PlayBroadcast) Unmarshal(dAtA []byte) error {
	var hasFields [1]uint64
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGambler
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PlayBroadcast: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PlayBroadcast: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OP", wireType)
			}
			var v int32
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGambler
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.OP = &v
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pos", wireType)
			}
			m.Pos = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGambler
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Pos |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			hasFields[0] |= uint64(0x00000001)
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field First", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGambler
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.First = bool(v != 0)
			hasFields[0] |= uint64(0x00000002)
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field History", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGambler
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGambler
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.History = append(m.History, &Cards{})
			if err := m.History[len(m.History)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGambler(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGambler
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}
	if hasFields[0]&uint64(0x00000001) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("pos")
	}
	if hasFields[0]&uint64(0x00000002) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("first")
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PlayRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGambler
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PlayRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PlayRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OP", wireType)
			}
			var v int32
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGambler
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.OP = &v
		case 2:
			if wireType == 0 {
				var v int32
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowGambler
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= (int32(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.Cards = append(m.Cards, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowGambler
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= (int(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthGambler
				}
				postIndex := iNdEx + packedLen
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				for iNdEx < postIndex {
					var v int32
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowGambler
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= (int32(b) & 0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.Cards = append(m.Cards, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field Cards", wireType)
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGambler(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGambler
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PlayResponse) Unmarshal(dAtA []byte) error {
	var hasFields [1]uint64
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGambler
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PlayResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PlayResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OP", wireType)
			}
			var v int32
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGambler
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.OP = &v
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ErrCode", wireType)
			}
			m.ErrCode = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGambler
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ErrCode |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			hasFields[0] |= uint64(0x00000001)
		default:
			iNdEx = preIndex
			skippy, err := skipGambler(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGambler
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}
	if hasFields[0]&uint64(0x00000001) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("errCode")
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PlayResultBroadcast) Unmarshal(dAtA []byte) error {
	var hasFields [1]uint64
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGambler
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PlayResultBroadcast: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PlayResultBroadcast: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OP", wireType)
			}
			var v int32
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGambler
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.OP = &v
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pos", wireType)
			}
			m.Pos = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGambler
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Pos |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			hasFields[0] |= uint64(0x00000001)
		case 3:
			if wireType == 0 {
				var v int32
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowGambler
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= (int32(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.Cards = append(m.Cards, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowGambler
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= (int(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthGambler
				}
				postIndex := iNdEx + packedLen
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				for iNdEx < postIndex {
					var v int32
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowGambler
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= (int32(b) & 0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.Cards = append(m.Cards, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field Cards", wireType)
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGambler(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGambler
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}
	if hasFields[0]&uint64(0x00000001) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("pos")
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *DeckEndBroadcast) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGambler
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DeckEndBroadcast: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DeckEndBroadcast: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OP", wireType)
			}
			var v int32
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGambler
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.OP = &v
		case 2:
			if wireType == 0 {
				var v int32
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowGambler
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= (int32(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.Score = append(m.Score, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowGambler
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= (int(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthGambler
				}
				postIndex := iNdEx + packedLen
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				for iNdEx < postIndex {
					var v int32
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowGambler
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= (int32(b) & 0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.Score = append(m.Score, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field Score", wireType)
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGambler(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGambler
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGambler(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGambler
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGambler
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGambler
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthGambler
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowGambler
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipGambler(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthGambler = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGambler   = fmt.Errorf("proto: integer overflow")
)

func init() { proto.RegisterFile("gambler.proto", fileDescriptorGambler) }

var fileDescriptorGambler = []byte{
	// 496 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x93, 0x4d, 0x6f, 0xd3, 0x30,
	0x1c, 0xc6, 0x97, 0x37, 0x8d, 0xfe, 0xcb, 0xa0, 0x84, 0x69, 0x8a, 0x90, 0x08, 0x55, 0x76, 0xe9,
	0xa9, 0x6a, 0xc3, 0xeb, 0x38, 0x20, 0xd1, 0x14, 0x01, 0x97, 0xad, 0xca, 0xb8, 0x20, 0x21, 0x21,
	0x37, 0xf1, 0xb6, 0x88, 0xb4, 0x0e, 0xb6, 0x27, 0xd4, 0x0b, 0x9f, 0x81, 0x03, 0x1f, 0x6a, 0x47,
	0x3e, 0x01, 0x42, 0xe5, 0x8b, 0x20, 0x3b, 0x75, 0x93, 0xd2, 0xb9, 0x54, 0xdc, 0xea, 0xa7, 0xf6,
	0xef, 0x79, 0xfe, 0x2f, 0x81, 0xbd, 0x73, 0x34, 0x19, 0xe7, 0x98, 0x76, 0x0b, 0x4a, 0x38, 0x71,
	0xcd, 0x62, 0x1c, 0xbc, 0x84, 0xdb, 0x31, 0x3e, 0xcf, 0x18, 0xc7, 0x34, 0xc6, 0x9f, 0x2f, 0x31,
	0xe3, 0xee, 0x3e, 0x98, 0x27, 0x23, 0xcf, 0x68, 0x1b, 0x1d, 0xe7, 0xb9, 0xdd, 0xef, 0xf5, 0xfa,
	0xb1, 0x79, 0x32, 0x72, 0x3d, 0xb0, 0xa7, 0x68, 0x82, 0x3d, 0xb3, 0x6d, 0x76, 0x1a, 0x03, 0xfb,
	0xea, 0xe7, 0x83, 0x9d, 0x58, 0x2a, 0xc1, 0x1b, 0x68, 0x55, 0x08, 0x56, 0x90, 0x29, 0xc3, 0x6b,
	0x8c, 0x50, 0x32, 0x7c, 0xd8, 0xc5, 0x94, 0x46, 0x24, 0x2d, 0x31, 0xce, 0x02, 0xa3, 0xc4, 0xe0,
	0x35, 0xc0, 0x69, 0xc6, 0x75, 0x39, 0x1e, 0x4a, 0xc6, 0x21, 0xc0, 0x04, 0xf1, 0xe4, 0xe2, 0xe3,
	0x5a, 0x9a, 0x86, 0xd4, 0x8f, 0x45, 0xa4, 0x08, 0x9a, 0x12, 0xa4, 0x49, 0xf3, 0x68, 0xab, 0x34,
	0xf7, 0xc1, 0x89, 0x10, 0x4d, 0x99, 0xbb, 0x0f, 0x4e, 0x22, 0x7e, 0x78, 0x46, 0xdb, 0xea, 0x38,
	0x71, 0x79, 0x08, 0xde, 0xc1, 0xad, 0x21, 0x46, 0xb9, 0xb8, 0x72, 0x4c, 0x78, 0x76, 0x36, 0x5b,
	0xb5, 0x09, 0x55, 0xe3, 0x0e, 0xc0, 0x2a, 0x08, 0x5b, 0xb1, 0x10, 0x42, 0x45, 0xb5, 0xea, 0xd4,
	0x0f, 0xe0, 0x46, 0x28, 0xcf, 0x4f, 0x13, 0x42, 0xf1, 0x80, 0x12, 0x94, 0x26, 0xe8, 0xef, 0x56,
	0x84, 0xaa, 0x9d, 0x3a, 0xb2, 0x07, 0xbb, 0x17, 0x19, 0xe3, 0x84, 0xce, 0x16, 0x6c, 0x75, 0x0c,
	0x86, 0xd0, 0x5a, 0xd2, 0xaf, 0x6d, 0x73, 0xa8, 0xda, 0x7c, 0x0f, 0x1c, 0x26, 0x6e, 0xad, 0xd0,
	0x4b, 0x29, 0x78, 0x0b, 0x77, 0x6a, 0x94, 0xeb, 0x7a, 0x1c, 0x6e, 0xdb, 0xe3, 0x14, 0xbc, 0x3a,
	0xea, 0x32, 0xe7, 0xfa, 0xa2, 0x1f, 0x6f, 0x2c, 0x7a, 0x19, 0xd8, 0x5a, 0x0f, 0xfc, 0xdd, 0x80,
	0x83, 0xa5, 0x4d, 0x84, 0xf2, 0x44, 0x6f, 0xf2, 0x44, 0x2d, 0x7b, 0x4a, 0xd1, 0x17, 0xe9, 0x72,
	0x43, 0x2d, 0xbb, 0x50, 0xc4, 0x3f, 0x39, 0xa1, 0xe9, 0x8a, 0x8b, 0x54, 0xaa, 0x00, 0xf6, 0x5a,
	0x80, 0x6a, 0xd6, 0x4e, 0x7d, 0xd6, 0x5f, 0x61, 0x6f, 0x94, 0xa3, 0x99, 0x3e, 0xcc, 0xd3, 0x7f,
	0x55, 0x7c, 0x96, 0x51, 0xc6, 0x65, 0x16, 0x95, 0xb2, 0x94, 0xdc, 0xc3, 0x6a, 0x05, 0xec, 0xb6,
	0xd5, 0x69, 0x86, 0x8d, 0x6e, 0x31, 0xee, 0xca, 0x75, 0xae, 0xb6, 0xe1, 0x08, 0x9a, 0xc2, 0x5f,
	0xb7, 0x08, 0xcf, 0xa4, 0xfb, 0x32, 0xba, 0x59, 0x8f, 0x3e, 0x84, 0x9b, 0xe5, 0x53, 0xcd, 0xf4,
	0x8f, 0xb6, 0x9a, 0xfe, 0x7b, 0xb8, 0xbb, 0xa0, 0x6c, 0x1a, 0x7c, 0xbf, 0xf7, 0x1f, 0xdf, 0xd1,
	0x0b, 0x68, 0x0d, 0x71, 0xf2, 0xe9, 0xd5, 0x34, 0xd5, 0x73, 0xfb, 0xaa, 0x40, 0xb5, 0xe9, 0xf2,
	0xbd, 0x3c, 0x0c, 0x5a, 0x57, 0x73, 0xdf, 0xf8, 0x31, 0xf7, 0x8d, 0x5f, 0x73, 0xdf, 0xf8, 0xf6,
	0xdb, 0xdf, 0xf9, 0x13, 0x00, 0x00, 0xff, 0xff, 0x9e, 0xe3, 0xe4, 0xcf, 0x3d, 0x05, 0x00, 0x00,
}
