// Do NOT edit this file manually

package protocol

const (
	MSG_CS_PingRequest             uint16 = 100
	MSG_SC_PingResponse            uint16 = 101
	MSG_CS_LoginRequest            uint16 = 102
	MSG_SC_LoginResponse           uint16 = 103
	MSG_CS_EnterGameRequest        uint16 = 104
	MSG_SC_EnterGameResponse       uint16 = 105
	MSG_CS_PlayerDataRequest       uint16 = 200
	MSG_SC_PlayerDataResponse      uint16 = 201
	MSG_CS_GMCommandRequest        uint16 = 202
	MSG_SC_GMCommandResponse       uint16 = 203
	MSG_CS_UseItemRequest          uint16 = 204
	MSG_SC_UseItemResponse         uint16 = 205
	MSG_CS_MarketBuyRequest        uint16 = 206
	MSG_SC_MarketBuyResponse       uint16 = 207
	MSG_SC_ItemUpdate              uint16 = 280
	MSG_SC_PlayerExpUpdate         uint16 = 281
	MSG_SC_NoticeUpdate            uint16 = 282
	MSG_CS_HeroLevelupRequest      uint16 = 300
	MSG_SC_HeroLevelupResponse     uint16 = 301
	MSG_CS_HeroRefineRequest       uint16 = 302
	MSG_SC_HeroRefineResponse      uint16 = 303
	MSG_SC_HeroInfoUpdateResponse  uint16 = 380
	MSG_CS_QuestListRequest        uint16 = 400
	MSG_SC_QuestListResponse       uint16 = 401
	MSG_CS_QuestOpRequest          uint16 = 402
	MSG_SC_QuestOpResponse         uint16 = 403
	MSG_SC_QuestUpdate             uint16 = 403
	MSG_CS_ChapterInfoRequest      uint16 = 500
	MSG_SC_ChapterInfoResponse     uint16 = 501
	MSG_CS_ChapterFightingRequest  uint16 = 502
	MSG_SC_ChapterFightingResponse uint16 = 503
	MSG_CS_ChapterRewardsRequest   uint16 = 504
	MSG_SC_ChapterRewardsResponse  uint16 = 505
	MSG_CS_ChapterLootRequest      uint16 = 506
	MSG_SC_ChapterLootResponse     uint16 = 507
)
